version: '3.4'

services:
  prometheusnetsample.webapi:
    container_name: prometheusnetsample_webapi
    image: ${DOCKER_REGISTRY-}prometheusnetsamplewebapi
    depends_on: 
        - prometheus
        - mytoxiproxy
    build:
      context: .
      dockerfile: TestAPI/Dockerfile
